{% set name = "sqllineage" %}
{% set version = "1.4.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqllineage-{{ version }}.tar.gz
  sha256: ec976f8212f2a921641e0eacc55e792e13369c410edefd90c7590d3a47f3f032

build:
  number: 0
  noarch: python
  entry_points:
    - sqllineage = sqllineage.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - networkx >=2.4
    - python >=3.8
    - sqlfluff >=2.0.0,<=2.0.3
    - sqlparse >=0.4.4

test:
  imports:
    - sqllineage
    - sqllineage.core
  commands:
    - pip check
    - sqllineage --help
  requires:
    - pip

about:
  home: https://github.com/reata/sqllineage
  summary: SQL Lineage Analysis Tool powered by Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
