{% set name = "sqllineage" %}
{% set version = "1.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqllineage-{{ version }}.tar.gz
  sha256: f4ed42f8bd88ce1822de0c3e5a8aa07cd1f5c9fa24c05f14b6af4c865fe571e2

build:
  number: 0
  noarch: python
  entry_points:
    - sqllineage = sqllineage.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - networkx >=2.4
    - python >=3.8
    - sqlparse ==0.4.4
    - sqlfluff ==3.0.3
    - sqlalchemy >=2.0.0

test:
  imports:
    - sqllineage
    - sqllineage.core
  commands:
    - pip check
    - sqllineage --help
  requires:
    - pip

about:
  home: https://github.com/reata/sqllineage
  summary: SQL Lineage Analysis Tool powered by Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
