{% set name = "sqllineage" %}
{% set version = "1.4.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqllineage-{{ version }}.tar.gz
  sha256: 131accb94189df94d2b6c391179de60d053c1278344144d5190108202e3bdee9

build:
  number: 0
  noarch: python
  entry_points:
    - sqllineage = sqllineage.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - networkx >=2.4
    - python >=3.8
    - sqlfluff ==2.3.3
    - sqlparse >=0.4.4

test:
  imports:
    - sqllineage
    - sqllineage.core
  commands:
    - pip check
    - sqllineage --help
  requires:
    - pip

about:
  home: https://github.com/reata/sqllineage
  summary: SQL Lineage Analysis Tool powered by Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
