{% set name = "sqllineage" %}
{% set version = "1.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqllineage-{{ version }}.tar.gz
  sha256: 5eeecfae4f5b29a127d8b065e0dc1d79ca589cde21204fc504a2e736bf235000

build:
  number: 0
  noarch: python
  entry_points:
    - sqllineage = sqllineage.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - flask
    - flask-cors
    - networkx >=2.4
    - python >=3.6
    - sqlparse >=0.3.1
    - werkzeug

test:
  imports:
    - sqllineage
    - sqllineage.core
  commands:
    - pip check
    - sqllineage --help
  requires:
    - pip

about:
  home: https://github.com/reata/sqllineage
  summary: SQL Lineage Analysis Tool powered by Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
